"""empty message

Revision ID: 32701c98ca0b
Revises: d7be526f1161
Create Date: 2024-04-16 11:08:24.604648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32701c98ca0b'
down_revision = 'd7be526f1161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('handle', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'handle')
    # ### end Alembic commands ###
