"""empty message

Revision ID: b7cf93b2417c
Revises: 338487b8cedd
Create Date: 2024-04-11 15:28:58.933133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7cf93b2417c'
down_revision = '338487b8cedd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('game', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_column('game', 'title')
    # ### end Alembic commands ###
