"""empty message

Revision ID: be74d6978319
Revises: 0da8d66fa7c1
Create Date: 2024-04-15 04:53:32.549116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be74d6978319'
down_revision = '0da8d66fa7c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_profile', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('game_profile', sa.Column('rank', sa.String(), nullable=True))
    op.add_column('platform', sa.Column('console', sa.String(), nullable=False))
    op.add_column('platform', sa.Column('logo', sa.String(), nullable=True))
    op.drop_column('platform', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_column('platform', 'logo')
    op.drop_column('platform', 'console')
    op.drop_column('game_profile', 'rank')
    op.drop_column('game_profile', 'level')
    # ### end Alembic commands ###
